apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: student-registration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:11
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: student-secret
              key: MARIADB_ROOT_PASSWORD

        - name: MARIADB_DATABASE
          value: studentdb

        - name: MARIADB_USER
          value: studentuser

        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: student-secret
              key: DB_PASSWORD

        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql

        - name: init-script
          mountPath: /docker-entrypoint-initdb.d

      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc

      - name: init-script
        configMap:
          name: mariadb-init