apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-registration-app
  namespace: student-registration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-registration
  template:
    metadata:
      labels:
        app: student-registration
    spec:
      containers:
      - name: student-registration
        image: damleshreyu/student-registration-app:v1
        ports:
        - containerPort: 80

        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: student-config
              key: DB_HOST

        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: student-config
              key: DB_NAME

        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: student-config
              key: DB_USER

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: student-secret
              key: DB_PASSWORD